@startuml
skinparam componentStyle uml2

!define ICONURL https://raw.githubusercontent.com/smartsdk/architecture-diagrams/smartsdk-template/dist
!includeurl ICONURL/common.puml
!includeurl ICONURL/fiware.puml
!includeurl ICONURL/smartsdk.puml

interface NGSI

package "IoT Service Enablement" {

package "IoT Backend" {
  FIWARE(idas,"Backend Device \n Management - IDAS",component)
  FIWARE(iotd,"IoT Discovery",component)
  FIWARE(iotb,"IoT Broker",component)
  NGSI -down- idas
  NGSI -down- iotd
  NGSI -down- iotb
}
package "IoT Edge" {
  FIWARE(iote,"IoT Data Edge \n Consolidation GE - Cepheus",component)
  NGSI -right- iote
}

@enduml
