@startuml

!define ICONURL https://raw.githubusercontent.com/smartsdk/architecture-diagrams/master/dist
!includeurl ICONURL/common.puml
!includeurl ICONURL/fiware.puml
!includeurl ICONURL/smartsdk.puml

    package "FrontEnd Smart City \n Application" as fesca{
      rectangle "-" as r1{
        [Home to user and \n managers] as htuam
        [Register / Edit \n health profile] as rehp
        [Subscribe to \n notifications] as stn
        [Subscribe to \n groups] as stg
        [Register / Edit user \n profile] as reup
        [Register / Edit user \n vehicle profile] as revp
        [View your \n generated events] as vyge
        [Register public \n transport] as rpt
        [Register transport schedule] as rts
      }
    }

    htuam -[hidden]right- reup
    rehp -[hidden]up- htuam

    rehp -[hidden]right- revp
    stn -[hidden]up- rehp

    stn -[hidden]right-vyge
    stg -[hidden]up- stn

    stg -[hidden]right- rpt
    rts-[hidden]up- rpt
    rts-[hidden]up- stg

    package "BackEnd Smart City \n Application" as besca{
      rectangle "-" as r{
        [Home to user and \n managers] as htuam1
        [Module to manage \n health profile] as mtmhp
        [Module to manage \n notifications] as mtmn
        [Module to manage to \n groups] as mtmg
        [Module to manage \n user profile] as mtmup
        [Module to manage \n vehicle profile] as mtmvp
        [Module to manage \n events] as mtme
        [Module to manage \n public transport] as mtmpt
        [Module to manage transport \n schedule] as mtmts
      }
      [Access Control] as ac
      database "Public \n transport \n database" as ptd{
      }
      database "User, disease \n and vehicle \n database" as udavd{
      }
    }

    htuam1 -[hidden]right- mtmup
    mtmhp -[hidden]up- htuam1

    mtmhp -[hidden]right- mtmvp
    mtmn -[hidden]up- mtmhp

    mtmn -[hidden]right- mtme
    mtmg -[hidden]up- mtmn

    mtmg -[hidden]right- mtmpt
    mtmts-[hidden]up- mtmg
    mtmts-[hidden]up- mtmpt

    mtmts <-down-> ac
    mtmts -down- ptd
    mtmts -down- udavd

    interface "Oauth 2 \n flow" as oadf

    oadf -[hidden]up- rts
    r1 - oadf

    [Identity Manager \n (Keyrock)] as imkr

    imkr-[hidden]up- oadf

    oadf -- imkr

    package "Route Service \n Enablement" as rse{
      [Routing \n wrapper] as rw
      [Public router (OTP)] as protp
      [Routing engine] as re
      interface "GTPS Data" as gtpsd
      interface "OSM" as osm
    }

    re -[hidden]right- re
    protp-[hidden]down- re
    rse -[hidden]up- ac
    rse -- besca
    protp -- rw : "JSON"
    re -- rw : "JSON"
    protp -- gtpsd
    protp -- osm
    re -- osm
    rw -[hidden]down- protp
    rw -[hidden]left- re

    package "Mobile Alerts for \n Smart City Scenario" as mafscs{
        [Mobile alert application \n for accidents, traffic jam, \n pollution, weather condition \n pollen, asthma attacks] as allalerts
        database "Alerts database" as ad
    }
    ad -[hidden]-allalerts
    allalerts -- ad

    package "Cosmos (to be developed)" as ctbd{
      [Cygnus] as cygnus
      [Big Data Analysis] as bdan
      [STH commet] as sthc
    }
    ctbd -[hidden]left- rse
    cygnus -- sthc
    cygnus -- bdan
    besca --cygnus

    package "SDK library for NGSI" as sdklfngsi{
      [Mobile device \n (location, acce- sensorslerometer, \n gyroscope)] as sensors
      database "Mobile data context \n (current version)" as mdcd
    }
    sdklfngsi -[hidden]- ctbd
    mdcd -[hidden]left- sensors

    package "IoT Device" as piotd{
      [Clouino] as cloudino
      [Humidity sensor] as hs
      [Temperature sensor] as ts
      [GPS sensor (in progress)] as gpss
    }
    cloudino -- hs
    cloudino -- gpss
    cloudino - ts
    interface "MQTT" as mqtt
    cloudino -- mqtt

    package "IoT Mobile Device" as iotmd{
      [Smart Spot] as spot
      [Gas detection sensor \n NO2, SO2, CO, O3] as gds
      [Temperature and humidity sensor] as tahs
      [GPS sensor \n (in progress)] as gpssip
    }
    spot - gds
    spot -- gpssip
    spot -- tahs
    interface "LWM2M" as lwm2m
    spot -- lwm2m

    package "Iot Fixed Device" as iotfd{
      [Smart spot] as ssp
      [Gas detection sensor \n NO2, SO2, CO, O3] as gds2
      [Temperature and humidity sensor] as tahs2
    }
    ssp -- gds2
    ssp -- tahs2
    ssp -- lwm2m

    tahs -[hidden]down- lwm2m
    tahs2 -[hidden]down- allalerts

    rse -[hidden]right- mafscs

    [Context Broker \n Orion] as cbo
    cbo -[hidden]left- mtmup

    interface "<font size=35 color=red>NGSI" as ngsi

    fesca -- besca : "JSON"
    besca ---- ngsi
    cbo ----- ngsi
    rw -- ngsi
    ngsi -- allalerts
    ngsi -- cygnus
    ngsi -- sensors
    ngsi -- cloudino

    package "IoT Backed" as iotb{
      [IoT Broker] as iotbr
      [IoT Discovery] as iotd
      [Backend device management \n IDAS] as bedmi
    }
    bedmi -- mqtt
    iotbr ------ ngsi
    iotd ------ ngsi
    bedmi ------ ngsi
    bedmi -[hidden]left- iotd
    iotbr  -[hidden]right- iotd
    bedmi -- lwm2m

@enduml
