@startuml;
skinparam componentStyle uml2

!define BASEURL https://raw.githubusercontent.com/smartsdk/architecture-diagrams/master
!includeurl BASEURL/data-management/Data-ContextManagement-SmartSDK-extension.puml
!includeurl BASEURL/iot-management/IoT-Service-Enablement-SmartSDK-extension.puml

package "SmartCity FrontEnd" as scfrontend {
	SMARTSDK(eventsgui,"Events GUI",component)
	SMARTSDK(notificationsgui,"Notifications GUI",component)
}

package "SmartCity BackEnd" as scbackend {
	SMARTSDK(eventsmgt,"Events Management",component)
	SMARTSDK(notificationsmgt,"Notifications Management",component)
}


notificationsgui -down- notificationsmgt
eventsgui -down- eventsmgt
notificationsmgt -down- NGSI
eventsmgt -down- NGSI

package "Mobile Alerts App" as mobilealerts {
	SMARTSDK(alert,"Alert Application",component)
}

[Location] as location
[Acceleration] as acceleration
[Heading] as heading


SMARTSDK(altertdata,"Alert\nDatamodel",database)
ctx -left- altertdata

alert -down- sdk

location -up- sdk
acceleration -up- sdk
heading -up- sdk

hide cosmos
hide timeseries
hide encryption
hide cep
hide ckan
hide kurento
hide iotse

@enduml
