@startuml;
skinparam componentStyle uml2

!define ICONURL https://raw.githubusercontent.com/smartsdk/architecture-diagrams/master/dist
!includeurl ICONURL/common.puml
!includeurl ICONURL/fiware.puml
!includeurl ICONURL/smartsdk.puml

package "Map Services" as mapservices {
	SMARTSDK(mapengine,"Map Engine",component)
}

package "Routing Services" as routingservices {
	SMARTSDK(routing,"Routing Engine",component)
	SMARTSDK(publicrouter,"Public Transport Router",component)
	SMARTSDK(pvtrouter,"Private Transport Router",component)

	routing -down- publicrouter
	routing -down- pvtrouter
}

mapengine -left- routing

Database GTFS as gtfs
gtfs -up- publicrouter

Database OSM as osm
osm -up- pvtrouter


[GPS Sensor] as gps1

[GPS Sensor] as gps2

!define BASEURL https://raw.githubusercontent.com/smartsdk/architecture-diagrams/master
!includeurl BASEURL/data-management/Data-ContextManagement-SmartSDK-extension.puml
!includeurl BASEURL/iot-management/IoT-Service-Enablement-SmartSDK-extension.puml

hide encryption
hide cep
hide ckan
hide kurento
hide cosmos
hide proximithings
hide iotd
hide iotb
hide iot1
hide iot2
hide iotedge
hide IETFCoAP
hide ctxaddon


mapengine -down- NGSI

NGSI -right- routing

cloudino -down- gps1

smartspot -down- gps2

@enduml
