@startuml;
skinparam componentStyle uml2

!define BASEURL https://raw.githubusercontent.com/smartsdk/architecture-diagrams/master
!includeurl BASEURL/data-management/Data-ContextManagement-SmartSDK-extension.puml

[Video \n Streaming] as vs

hide encryption
hide timeseries
hide sth
hide ckan
hide cep
hide sdk

package "SmartSecurity FrontEnd" as scfrontend {
	SMARTSDK(eventsgui,"Events GUI",component)
}

package "SmartSecurity BackEnd" as scbackend {
	SMARTSDK(eventsmgt,"Events Management",component)
  SMARTSDK(secfilter,"Video Security Events\nDetection",component)
}

SMARTSDK(seceventdata,"Security Event\nDatamodel",database)
ctx -down- seceventdata

secfilter -left- kurento
secfilter -right- eventsmgt
eventsmgt -up- eventsgui

interface RTSP

vs -up- RTSP
RTSP -up- kurento

@enduml
